// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryothocmecdgmjawcgyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5b3Rob2NtZWNkZ21qYXdjZ3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODI4NDMsImV4cCI6MjA2NTU1ODg0M30.KHJH5w2vxml1WY6_RXi3Qnx9JRknV5R6bj07sdsX7Ek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);